create table if not exists chats (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  role text not null,
  message text not null
);
